version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
      - ./csvserver.env:/csvserver/csvserver.env
    command: /csvserver/csvserver /csvserver/inputdata/inputFile
    restart: always
